services:
  - type: web
    name: anistream
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true

  - type: worker
    name: anistream-telegram-bot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python telegram_uploader_bot/telegram_bridge_bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true

databases:
  - name: anistream-db
    databaseName: anistream
    user: anistream
