# Generated by Django 6.0.2 on 2026-03-18 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Anime nomini kiriting', max_length=200, verbose_name='Anime nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text="Anime haqida qisqacha ma'lumot", verbose_name="Qisqacha ta'rifi")),
                ('anime_type', models.CharField(choices=[('tv', 'TV Serial'), ('movie', 'Film'), ('ova', 'OVA'), ('special', 'Maxsus')], default='tv', max_length=20, verbose_name='Anime turi')),
                ('status', models.CharField(choices=[('ongoing', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('upcoming', 'Tez orada')], default='ongoing', max_length=20, verbose_name='Holati')),
                ('release_year', models.IntegerField(help_text='1960 dan 2030 gacha', validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2030)], verbose_name='Chiqarilgan yili')),
                ('rating', models.FloatField(default=0.0, help_text='0.0 dan 10.0 gacha', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Reyting')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('image_url', models.URLField(default='https://via.placeholder.com/300x400', help_text='Anime rasmi URL manzili', max_length=500, verbose_name='Rasm havolasi')),
                ('banner_url', models.URLField(blank=True, help_text='Katta banner rasm (ixtiyoriy)', max_length=500, null=True, verbose_name='Banner rasm')),
                ('trailer_url', models.URLField(blank=True, help_text='Trailer URL (ixtiyoriy)', max_length=500, null=True, verbose_name='Trailer video')),
                ('studio', models.CharField(blank=True, max_length=200, verbose_name='Studiya')),
                ('age_rating', models.CharField(default='13+', max_length=10, verbose_name='Yosh chegarasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animelar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Janr nomi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anime.anime')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(help_text='1 dan boshlanadi', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qism raqami')),
                ('title', models.CharField(blank=True, help_text='Qismning nomi (ixtiyoriy)', max_length=200, null=True, verbose_name='Qism nomi')),
                ('video_file', models.FileField(blank=True, help_text='Kompyuterdan video yuklash', null=True, upload_to='videos/', verbose_name='Videoni kompyuterdan yuklash')),
                ('video_url', models.URLField(blank=True, help_text='Tashqi video silkasi', max_length=500, null=True, verbose_name='Video silkasi (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Qism (Episode)',
                'verbose_name_plural': 'Qismlar (Episodes)',
                'ordering': ['anime', 'episode_number'],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='anime.genre', verbose_name='Janrlar'),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Matn')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Vergul bilan ajrating', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kun")),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='anime.anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='in_watchlist', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Profili',
                'verbose_name_plural': 'Foydalanuvchi Profillari',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_progress', models.IntegerField(default=0, help_text='Daqiqalarda')),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ko'rish Tarixi",
                'verbose_name_plural': "Ko'rish Tarixi",
                'ordering': ['-last_watched'],
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['anime', 'episode_number'], name='anime_episo_anime_i_31f856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'episode_number')},
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['-created_at'], name='anime_anime_created_3eb771_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['rating'], name='anime_anime_rating_c07b47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'anime', 'episode')},
        ),
    ]
