# Generated by Django 6.0.2 on 2026-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Anime nomi')),
                ('description', models.TextField(verbose_name="Qisqacha ta'rifi")),
                ('release_year', models.IntegerField(verbose_name='Chiqarilgan yili')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
