# Generated by Django 5.0.4 on 2026-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x400', max_length=500, verbose_name='Rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
