# Generated by Django 6.0.5 on 2026-06-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=20, verbose_name='Hafta kuni')),
                ('episode_number', models.PositiveIntegerField(default=1, verbose_name='Chiqadigan qism')),
                ('fandub', models.CharField(blank=True, default='AniStream', max_length=100, null=True, verbose_name='Fandub studiya')),
                ('air_time', models.CharField(blank=True, help_text='Masalan: 18:00', max_length=10, null=True, verbose_name='Chiqish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='anime.movie', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Anime Jadvali',
                'verbose_name_plural': 'Anime Jadvallari',
                'ordering': ['day_of_week', 'order'],
            },
        ),
    ]
