# Generated by Django 6.0.2 on 2026-03-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_episode_telegram_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='telegram_channel_post_url',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='telegram_message_id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Kichik videolar uchun (Bot API)', max_length=255, null=True, verbose_name='Telegram file_id'),
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Qisqa video/lavha nomi', max_length=200, verbose_name='Lavha nomi')),
                ('telegram_file_id', models.CharField(help_text="Bot orqali yuklangan qisqa video ID'si", max_length=255, verbose_name='Telegram file_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='anime.anime', verbose_name='Tegishli Anime')),
            ],
            options={
                'verbose_name': 'Lavha (Short)',
                'verbose_name_plural': 'Lavhalar (Shorts)',
                'ordering': ['-created_at'],
            },
        ),
    ]
