# Generated by Django 5.0.4 on 2026-02-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_image_url_alter_anime_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(verbose_name='Qism raqami (masalan: 1)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qism nomi')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videoni kompyuterdan yuklash')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Yoki video silkasini yozing (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
