# Generated by Django 6.0.5 on 2026-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_add_anime_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_stickers', models.BooleanField(default=True, verbose_name='Stikerlarga ruxsat')),
                ('allow_emojis', models.BooleanField(default=True, verbose_name='Emojilarga ruxsat')),
                ('default_theme', models.CharField(choices=[('dark', "Qorong'i"), ('light', "Yorug'"), ('system', 'Tizim sozlamasi')], default='dark', max_length=20, verbose_name='Standart mavzu')),
                ('primary_color', models.CharField(default='#FF5733', max_length=20, verbose_name='Asosiy rang (HEX)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='app_backgrounds/', verbose_name='Orqa fon rasmi (URL)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilova Sozlamasi',
                'verbose_name_plural': 'Ilova Sozlamalari',
            },
        ),
    ]
