# Generated by Django 6.0.5 on 2026-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='bg_image',
            field=models.CharField(blank=True, help_text='Foydalanuvchi tanlagan fon rasmi URL si', max_length=255, null=True),
        ),
    ]
