# Generated by Django 6.0.2 on 2026-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_episode_telegram_channel_post_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, help_text="MTProto stream uchun (Kanal/Guruhdagi xabar ID'si)", null=True, verbose_name='Telegram message_id'),
        ),
    ]
