# Generated by Django 6.0.2 on 2026-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_episode_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='telegram_channel_post_url',
            field=models.URLField(blank=True, help_text='Telegram kanaldagi xabar havolasi', max_length=500, null=True, verbose_name='Telegram post URL'),
        ),
    ]
