# Generated by Django 6.0.5 on 2026-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_usersettings_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('dark', "Qorong'i"), ('white', 'Oq'), ('rose', "Qizil / Ro'za"), ('premium', "Premium (To'q binafsha)"), ('pink', 'Pushti'), ('ocean', 'Okean'), ('forest', "O'rmon")], default='dark', max_length=20),
        ),
    ]
