# Generated by Django 6.0.5 on 2026-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_sitesettings_story_remove_anime_banner_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
