# Generated by Django 6.0.5 on 2026-06-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_remove_newspost_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='video_url',
        ),
    ]
